In [3]:
import pandas as pd  #Import Lib
import numpy as np

In [4]:
ratings = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\movie_lense\u.data",
    sep="\t",
    names=["user_id", "movie_id", "ratings", "timestamp"]
)

ratings.head()

   user_id  movie_id  ratings  timestamp
0      196       242        3  881250949
1      186       302        3  891717742
2       22       377        1  878887116
3      244        51        2  880606923
4      166       346        1  886397596

In [5]:
movies = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\movie_lense\u.item",
    sep="|",
    encoding="latin-1",
    header=None
)

movies.head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [6]:
movies = movies[[0,1]]   #Keeping only required columns

movies.columns = ['movie_id', "movie_title"]

movies.head()

   movie_id        movie_title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [7]:
users = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\movie_lense\u.user",
    sep="|",
    names=["user_id", "age", "gender", "occupation", "zip_code"]
)

users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [8]:
latest_movies = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\latest_movies_2025\Latest 2025 movies Datasets.csv"
)

latest_movies.head()

,Unnamed: 0,title,release_date,original_language,popularity,vote_count,vote_average,overview
0,0,Our Fault,2025-10-15,es,1096.6654,302,7.869,Jenna and Lion's wedding brings about the long...
1,1,Inside Furioza,2025-10-14,pl,384.3220,27,6.593,"In the wake of murder, new Furioza leader Gold..."
2,2,Captain Hook - The Cursed Tides,2025-07-11,en,370.1091,15,5.000,In the aftermath of a devastating defeat by hi...
3,3,War of the Worlds,2025-07-29,en,327.8760,642,4.400,Will Radford is a top analyst for Homeland Sec...
4,4,The Conjuring: Last Rites,2025-09-03,en,284.0186,1065,6.972,Paranormal investigators Ed and Lorraine Warre...

In [9]:
latest_movies = latest_movies[
    [
        "title",
        "overview",
        "release_date",
        "vote_average",
        "popularity"
    ]
]

latest_movies.head()

,title,overview,release_date,vote_average,popularity
0,Our Fault,Jenna and Lion's wedding brings about the long...,2025-10-15,7.869,1096.6654
1,Inside Furioza,"In the wake of murder, new Furioza leader Gold...",2025-10-14,6.593,384.3220
2,Captain Hook - The Cursed Tides,In the aftermath of a devastating defeat by hi...,2025-07-11,5.000,370.1091
3,War of the Worlds,Will Radford is a top analyst for Homeland Sec...,2025-07-29,4.400,327.8760
4,The Conjuring: Last Rites,Paranormal investigators Ed and Lorraine Warre...,2025-09-03,6.972,284.0186

In [10]:
print(ratings.shape)
print(movies.shape)
print(users.shape)
print(latest_movies.shape)

(100000, 4)
(1682, 2)
(943, 5)
(10000, 5)

In [11]:
ratings.info()
movies.info()
latest_movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100000 non-null  int64
 1   movie_id   100000 non-null  int64
 2   ratings    100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 1682 entries, 0 to 1681
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     1682 non-null   int64
 1   movie_title  1682 non-null   str
dtypes: int64(1), str(1)
memory usage: 26.4 KB
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         10000 non-null  str
 1   overview      9758 non-null   str
 2   release_date  9951 non-null   str
 3   vote_average  10000 non-null  float64
 4   popularity    10000 non-null  float64
dtypes: float64(2), str(3)
memory usage: 390.8 KB

In [12]:
latest_movies.isnull().sum()   #checking Missing value

title             0
overview        242
release_date     49
vote_average      0
popularity        0
dtype: int64

In [13]:
latest_movies = latest_movies.dropna(subset=["overview"])
#removed all NaN values in overview

In [14]:
latest_movies.shape
latest_movies.isnull().sum()

title            0
overview         0
release_date    34
vote_average     0
popularity       0
dtype: int64

In [15]:
latest_movies["release_date"] = pd.to_datetime(
    latest_movies["release_date"],
    errors="coerce"  #Give NaT(Not a Time) to invalid dates
)

In [16]:
latest_movies["release_year"] = (
    latest_movies["release_date"].dt.year #new feature
)

In [17]:
latest_movies.info()

<class 'pandas.DataFrame'>
Index: 9758 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         9758 non-null   str
 1   overview      9758 non-null   str
 2   release_date  9724 non-null   datetime64[us]
 3   vote_average  9758 non-null   float64
 4   popularity    9758 non-null   float64
 5   release_year  9724 non-null   float64
dtypes: datetime64[us](1), float64(3), str(2)
memory usage: 533.6 KB

In [ ]:
latest_movies[latest_movies['release_date'].isnull()]
#Output of missing columns

In [19]:
movie_ratings = pd.merge(
    ratings,
    movies,
    on="movie_id" #merge movie based on movie_id
)

movie_ratings.head()

   user_id  movie_id  ratings  timestamp                 movie_title
0      196       242        3  881250949                Kolya (1996)
1      186       302        3  891717742    L.A. Confidential (1997)
2       22       377        1  878887116         Heavyweights (1994)
3      244        51        2  880606923  Legends of the Fall (1994)
4      166       346        1  886397596         Jackie Brown (1997)

In [20]:
movie_ratings = movie_ratings.drop("timestamp", axis=1)

In [21]:
movie_ratings.head()

   user_id  movie_id  ratings                 movie_title
0      196       242        3                Kolya (1996)
1      186       302        3    L.A. Confidential (1997)
2       22       377        1         Heavyweights (1994)
3      244        51        2  Legends of the Fall (1994)
4      166       346        1         Jackie Brown (1997)

In [22]:
#Most rated movies
#------------------
movie_ratings["movie_title"].value_counts().head(10)

movie_title
Star Wars (1977)                 583
Contact (1997)                   509
Fargo (1996)                     508
Return of the Jedi (1983)        507
Liar Liar (1997)                 485
English Patient, The (1996)      481
Scream (1996)                    478
Toy Story (1995)                 452
Air Force One (1997)             431
Independence Day (ID4) (1996)    429
Name: count, dtype: int64

In [23]:
#Highest avg-rated movies - this is not fair even one movie with one 5 ratings take the first place 
#------------------
movie_ratings.groupby("movie_title")["ratings"]\
.mean()\
.sort_values(ascending=False)\
.head(10)

movie_title
Aiqing wansui (1994)                                 5.0
Entertaining Angels: The Dorothy Day Story (1996)    5.0
Santa with Muscles (1996)                            5.0
Prefontaine (1997)                                   5.0
They Made Me a Criminal (1939)                       5.0
Saint of Fort Washington, The (1993)                 5.0
Great Day in Harlem, A (1994)                        5.0
Star Kid (1997)                                      5.0
Marlene Dietrich: Shadow and Light (1996)            5.0
Someone Else's America (1995)                        5.0
Name: ratings, dtype: float64

In [24]:
movie_ratings.to_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\processed\movie_ratings.csv",
    index=False
)

In [25]:
latest_movies.to_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\processed\latest_movies_clean.csv",
    index=False
)

In [29]:
movie_ratings.describe()

            user_id       movie_id        ratings
count  100000.00000  100000.000000  100000.000000
mean      462.48475     425.530130       3.529860
std       266.61442     330.798356       1.125674
min         1.00000       1.000000       1.000000
25%       254.00000     175.000000       3.000000
50%       447.00000     322.000000       4.000000
75%       682.00000     631.000000       4.000000
max       943.00000    1682.000000       5.000000

In [32]:
movie_ratings["ratings"].value_counts()

ratings
4    34174
3    27145
5    21201
2    11370
1     6110
Name: count, dtype: int64