In [1]:
import pandas as pd
import numpy as np

In [2]:
movie_ratings = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\processed\movie_ratings.csv"
)

movie_ratings.head()

   user_id  movie_id  ratings                 movie_title
0      196       242        3                Kolya (1996)
1      186       302        3    L.A. Confidential (1997)
2       22       377        1         Heavyweights (1994)
3      244        51        2  Legends of the Fall (1994)
4      166       346        1         Jackie Brown (1997)

In [3]:
user_movie_matrix = movie_ratings.pivot_table(
    index="user_id",
    columns="movie_title",
    values="ratings"
) # Makes normal columns into User-Item Matrix

In [4]:
user_movie_matrix.head()
user_movie_matrix.shape
#rows-> users && columns-> movies

(943, 1664)

In [5]:
user_movie_matrix_filled = (
    user_movie_matrix.fillna(0)
) # replace empty values with zero

In [6]:
from sklearn.metrics.pairwise import cosine_similarity
#Compute Similarity Matrix
#rows-> movies && columns-> users

In [7]:
movie_similarity = cosine_similarity(
    user_movie_matrix_filled.T
) #can't able to see it because of ndarray format

In [8]:
movie_similarity_df = pd.DataFrame(
    movie_similarity,
    index=user_movie_matrix.columns,
    columns=user_movie_matrix.columns
) # can see output of movie similarity

In [9]:
movie_similarity_df["Star Wars (1977)"]\
.sort_values(ascending=False)\
.head(10)  #shows top 10 movies similar to respective movie

movie_title
Star Wars (1977)                             1.000000
Return of the Jedi (1983)                    0.884476
Raiders of the Lost Ark (1981)               0.764885
Empire Strikes Back, The (1980)              0.749819
Toy Story (1995)                             0.734572
Godfather, The (1972)                        0.697332
Independence Day (ID4) (1996)                0.692837
Indiana Jones and the Last Crusade (1989)    0.689343
Fargo (1996)                                 0.686533
Silence of the Lambs, The (1991)             0.676428
Name: Star Wars (1977), dtype: float64

In [10]:
movie_similarity_df.head(3)

movie_title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
movie_title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),1.000000,0.000000,0.024561,0.099561,0.185236,0.159265,0.000000,0.052203,0.000000,0.033326,...,0.000000,0.000000,0.000000,0.027774,0.118840,0.142315,0.029070,0.000000,0.110208,0.0
1-900 (1994),0.000000,1.000000,0.014139,0.009294,0.007354,0.004702,0.010055,0.067038,0.000000,0.000000,...,0.152499,0.015484,0.000000,0.069284,0.018243,0.023408,0.006694,0.079640,0.042295,0.0
101 Dalmatians (1996),0.024561,0.014139,1.000000,0.167006,0.061105,0.143878,0.203781,0.225803,0.027642,0.092337,...,0.000000,0.021965,0.030905,0.274877,0.204267,0.101199,0.056976,0.172155,0.045714,0.0

In [11]:
movie_similarity_df["Star Wars (1977)"]\
.sort_values(ascending=False)\
.iloc[1:11]  #removes self similarity

movie_title
Return of the Jedi (1983)                    0.884476
Raiders of the Lost Ark (1981)               0.764885
Empire Strikes Back, The (1980)              0.749819
Toy Story (1995)                             0.734572
Godfather, The (1972)                        0.697332
Independence Day (ID4) (1996)                0.692837
Indiana Jones and the Last Crusade (1989)    0.689343
Fargo (1996)                                 0.686533
Silence of the Lambs, The (1991)             0.676428
Star Trek: First Contact (1996)              0.673975
Name: Star Wars (1977), dtype: float64

In [12]:
movie_similarity_df.columns[:20]

Index([''Til There Was You (1997)', '1-900 (1994)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)', '187 (1997)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '3 Ninjas: High Noon At Mega Mountain (1998)', '39 Steps, The (1935)',
       '8 1/2 (1963)', '8 Heads in a Duffel Bag (1997)', '8 Seconds (1994)',
       'A Chef in Love (1996)', 'Above the Rim (1994)',
       'Absolute Power (1997)', 'Abyss, The (1989)',
       'Ace Ventura: Pet Detective (1994)',
       'Ace Ventura: When Nature Calls (1995)',
       'Across the Sea of Time (1995)'],
      dtype='str', name='movie_title')

In [13]:
movie_similarity_df["2001: A Space Odyssey (1968)"]\
.sort_values(ascending=False)\
.iloc[1:11]

movie_title
Raiders of the Lost Ark (1981)                                                 0.665146
Blade Runner (1982)                                                            0.660571
Graduate, The (1967)                                                           0.654458
Apocalypse Now (1979)                                                          0.644447
Brazil (1985)                                                                  0.637751
E.T. the Extra-Terrestrial (1982)                                              0.631199
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)    0.628854
Amadeus (1984)                                                                 0.627704
Monty Python and the Holy Grail (1974)                                         0.624176
Forrest Gump (1994)                                                            0.619470
Name: 2001: A Space Odyssey (1968), dtype: float64

**Movie_lens_latest**

In [2]:
ratings = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\movie_lens_latest\ratings.csv"
)

movies = pd.read_csv(
    r"C:\Dev\projects\movie_recommemdation_agent\data\raw\movie_lens_latest\movies.csv"
)

In [12]:
ratings.shape
movies.shape

print(ratings.columns)
print(movies.columns)

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='str')
Index(['movieId', 'title', 'genres'], dtype='str')

In [11]:
movie_ratings = ratings.merge(
    movies,
    on="movieId"
)

In [13]:
print(movie_ratings.shape)
print(movie_ratings.head())

(100836, 6)
   userId  movieId  rating  timestamp                        title  \
0       1        1     4.0  964982703             Toy Story (1995)
1       1        3     4.0  964981247      Grumpier Old Men (1995)
2       1        6     4.0  964982224                  Heat (1995)
3       1       47     5.0  964983815  Seven (a.k.a. Se7en) (1995)
4       1       50     5.0  964982931   Usual Suspects, The (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                               Comedy|Romance
2                        Action|Crime|Thriller
3                             Mystery|Thriller
4                       Crime|Mystery|Thriller

In [17]:
movie_user_matrix = movie_ratings.pivot_table(
    index="title",
    columns="userId",
    values="rating"
).fillna(0)

In [18]:
print(movie_user_matrix.shape)

(9719, 610)

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

movie_similarity = cosine_similarity(
    movie_user_matrix
)

In [21]:
similarity_df = pd.DataFrame(
    movie_similarity,
    index=movie_user_matrix.index,
    columns=movie_user_matrix.index
)

In [23]:
print(similarity_df.shape)

(9719, 9719)

In [22]:
print(
    similarity_df.loc[
        "Interstellar (2014)"
    ].sort_values(ascending=False).head(10)
)

title
Interstellar (2014)               1.000000
Inception (2010)                  0.608150
Django Unchained (2012)           0.587284
Dark Knight Rises, The (2012)     0.582879
Edge of Tomorrow (2014)           0.570106
The Imitation Game (2014)         0.567939
Avengers, The (2012)              0.555597
Deadpool (2016)                   0.554588
The Martian (2015)                0.546774
Guardians of the Galaxy (2014)    0.539885
Name: Interstellar (2014), dtype: float64

In [24]:
def recommend_cf_movies(movie_name, top_n=10):
    similar_movies = ( similarity_df[movie_name]
        .sort_values(ascending=False)
        .iloc[1:top_n+1]
    )
    
    return similar_movies.index.tolist()

In [25]:
print(
    recommend_cf_movies(
        "Interstellar (2014)"
    )
)

['Inception (2010)', 'Django Unchained (2012)', 'Dark Knight Rises, The (2012)', 'Edge of Tomorrow (2014)', 'The Imitation Game (2014)', 'Avengers, The (2012)', 'Deadpool (2016)', 'The Martian (2015)', 'Guardians of the Galaxy (2014)', 'Grand Budapest Hotel, The (2014)']

In [1]:
import sys
sys.path.append("../src")

In [2]:
from semantic_recommender import recommend_semantic_movies

semantic_results = recommend_semantic_movies(
    "Interstellar"
)

print(semantic_results)

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Dev\\projects\\movie_recommemdation_agent\\data\\embeddings\\similarity_matrix.pkl'